#!/usr/bin/env bash
# Regenerate INDEX.md — a token-cheap map of the trading repo corpus.
# Run from the Trading folder:  bash build_index.sh
set -u
cd "$(dirname "$0")" 2>/dev/null || true
ROOT="$(pwd)"
OUT="INDEX.auto.md"   # raw listing; fold useful bits into the curated INDEX.md by hand

{
  echo "# Trading Corpus Index"
  echo
  echo "_Auto-generated by build_index.sh on $(date -u +%Y-%m-%dT%H:%MZ). Read-only reference library._"
  echo
  echo "When researching, read this file first. Only open a repo's actual source when an"
  echo "entry below points you there. Never load a whole repo into context."
  echo
} > "$OUT"

for d in */ ; do
  name="${d%/}"
  [ "$name" = "node_modules" ] && continue
  {
    echo "---"
    echo
    echo "## $name"
    echo

    # First real paragraph(s) of the README, trimmed
    readme=$(ls "$name"/README* 2>/dev/null | head -1 || true)
    if [ -n "${readme:-}" ]; then
      grep -vE '^\s*(<|!\[|\[!\[|#{1,6}\s|=+\s*$|-{3,}\s*$)' "$readme" \
        | grep -vE '^\s*$' \
        | head -12 \
        | cut -c1-200
      echo
    fi

    # Language / entry points
    echo "**Structure:**"
    top=$(find "$name" -maxdepth 1 -type d ! -name "$name" ! -name '.*' -printf '%f ' 2>/dev/null || true)
    echo " - top dirs: ${top:-none}"
    pyc=$(find "$name" -name '*.py' -not -path '*/.*' 2>/dev/null | wc -l)
    rsc=$(find "$name" -name '*.rs' -not -path '*/.*' 2>/dev/null | wc -l)
    echo " - files: ${pyc} .py, ${rsc} .rs"
    echo

    # Files whose path hints at reusable concepts
    echo "**Concept files (grep targets):**"
    find "$name" -type f \( -name '*.py' -o -name '*.rs' -o -name '*.ipynb' \) -not -path '*/.*' 2>/dev/null \
      | grep -iE '(risk|sizing|position|kelly|drawdown|backtest|strateg|indicator|signal|portfolio|optim|execution|order|slippage|walk.?forward|montecarlo|sharpe|regime)' \
      | sed "s|^| - |" \
      | head -25
    echo
  } >> "$OUT"
done

echo "Wrote $ROOT/$OUT ($(wc -l < "$OUT") lines, $(wc -c < "$OUT") bytes)"
