# Spec: Genesis Markdown/30-MCP/genesis-charting-mcp.md
"""Markup Spec -> a PineScript indicator, for the chart you actually look at.

genesis-tradingview-mcp.md's design note is the whole reason this file exists:

> **Compile, don't click.** The Desktop renderer works by compiling the spec into
> a Pine indicator and loading it through the editor -- not by simulating mouse
> drags on the chart. Text and keystrokes are a far more robust automation
> surface than price->pixel math, and Genesis ends up owning exactly one
> indicator, so your hand-drawn objects are never touched.

Three properties fall out of compiling rather than drawing, and each one is a
failure mode avoided rather than a nicety:

**Nothing of yours is touched.** Genesis owns one indicator. Removing it removes
every mark Genesis made, and no operation it performs can delete a line you drew.
A drag-based automation shares a canvas with your work and eventually loses an
argument with it.

**No price->pixel arithmetic.** Converting a price to a screen coordinate needs
the chart's scale, which changes when you scroll. Every such conversion is a
chance to draw a level at the wrong price -- silently, and looking authoritative.
Pine takes prices.

**The same object drives both renderers.** The PNG in the vault and the overlay
on your screen come from one spec, so what you look at is what the vision model
read. Two drawing paths would be two drawings that slowly diverge.

The generated source is deterministic: the same spec compiles to the same
characters, so a diff between two versions of an indicator is a diff between two
readings of the chart.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from genesis.charting.spec import (
    Fib,
    Level,
    Line,
    Marker,
    MarkupSpec,
    Projection,
    TextNote,
    TradePlan,
    Zone,
)

__all__ = ["INDICATOR_NAME", "compile_pine"]

#: The one indicator Genesis owns on your chart. Fixed, because "remove the
#: Genesis overlay" has to mean one unambiguous thing.
INDICATOR_NAME = "Genesis Markup"

#: Pine's per-script object budget is finite and the spec's cap is 8, so this is
#: never binding in practice -- it is here so that a hand-built spec cannot
#: produce a script TradingView refuses to compile.
MAX_OBJECTS = 60

_COLORS = {
    "resistance": "#d95926",
    "support": "#3987e5",
    "pivot": "#898781",
    "vwap": "#c98500",
    "poc": "#9085e9",
    "value_area": "#9085e9",
    "ma": "#d55181",
}
_ZONE_COLORS = {
    "fvg": "#3987e5",
    "demand": "#3987e5",
    "supply": "#d95926",
    "value_area": "#9085e9",
    "order_block": "#d55181",
    "orb": "#c98500",
}


def compile_pine(spec: MarkupSpec, *, version: int = 5) -> str:
    """The spec as a Pine v5 indicator, ready to paste or load over CDP.

    Every drawing is created once inside ``if barstate.islastconfirmedhistory``
    rather than on every bar. Pine re-executes the script per bar, and a script
    that creates a line each time hits the object limit and then silently drops
    the oldest ones -- which on a markup overlay means levels quietly vanishing
    from the top of the chart.
    """
    lines: list[str] = [
        "// Generated by Genesis — do not edit.",
        f"// spec {spec.id} · {spec.symbol} {spec.timeframe} · as of {spec.as_of.isoformat()}",
        f"// Regenerate with genesis-charting-mcp compile_pine, spec {spec.id}.",
        f"//@version={version}",
        f'indicator("{INDICATOR_NAME}", overlay=true, max_lines_count=500, '
        f"max_labels_count=500, max_boxes_count=500)",
        "",
        "// One-shot: draw on the last confirmed bar only. Pine re-runs per bar,",
        "// and re-creating objects every bar exhausts the object budget, after",
        "// which TradingView drops the oldest silently.",
        "if barstate.islastconfirmedhistory",
    ]

    drawn = 0
    for annotation in spec.annotations:
        if drawn >= MAX_OBJECTS:
            break
        body = _emit(annotation, spec)
        if body:
            lines.extend("    " + row for row in body)
            drawn += 1

    lines.extend(
        [
            "",
            _header_label(spec),
            "",
        ]
    )
    return "\n".join(lines)


def _emit(annotation: Any, spec: MarkupSpec) -> list[str]:
    if isinstance(annotation, Level):
        return _level(annotation)
    if isinstance(annotation, Zone):
        return _zone(annotation)
    if isinstance(annotation, (Projection, Line)):
        return _line(annotation, dashed=isinstance(annotation, Projection))
    if isinstance(annotation, TradePlan):
        return _trade_plan(annotation)
    if isinstance(annotation, Marker):
        return _marker(annotation)
    if isinstance(annotation, Fib):
        return _fib(annotation)
    if isinstance(annotation, TextNote):
        return _text(annotation)
    return []


def _level(level: Level) -> list[str]:
    colour = _COLORS.get(level.type, "#898781")
    # Width carries strength, so a 0.9 level is visibly heavier than a 0.3 one
    # without needing a second colour scale.
    width = 1 if level.strength < 0.5 else (2 if level.strength < 0.8 else 3)
    return [
        f"line.new(bar_index - 200, {level.price:.6f}, bar_index + 20, "
        f"{level.price:.6f}, extend=extend.right, "
        f'color=color.new(color.rgb({_rgb(colour)}), {_alpha(level.strength)}), '
        f"width={width})",
        f"label.new(bar_index + 20, {level.price:.6f}, "
        f'"{_escape(level.label)}  {level.price:,.2f}", '
        f"style=label.style_label_left, "
        f"color=color.new(color.rgb({_rgb(colour)}), 15), "
        f"textcolor=color.white, size=size.small, "
        f'tooltip="{_escape(level.why)}")',
    ]


def _zone(zone: Zone) -> list[str]:
    colour = _ZONE_COLORS.get(zone.subtype, "#898781")
    return [
        f"box.new(bar_index - 200, {zone.to_price:.6f}, bar_index + 20, "
        f"{zone.from_price:.6f}, "
        f"border_color=color.new(color.rgb({_rgb(colour)}), 40), "
        f"bgcolor=color.new(color.rgb({_rgb(colour)}), 88), "
        f'text="{_escape(zone.label)}", text_color=color.rgb({_rgb(colour)}), '
        f"text_size=size.tiny)",
    ]


def _line(line: Line, *, dashed: bool) -> list[str]:
    (t0, p0), (t1, p1) = line.points[0], line.points[-1]
    style = "line.style_dashed" if dashed else "line.style_solid"
    return [
        f"line.new({_time(t0)}, {p0:.6f}, {_time(t1)}, {p1:.6f}, "
        f"xloc=xloc.bar_time, extend=extend.right, style={style}, "
        f"color=color.new(color.rgb(195, 194, 183), 25), width=2)",
        f"label.new({_time(t1)}, {p1:.6f}, \"{_escape(line.label)}\", "
        f"xloc=xloc.bar_time, style=label.style_none, "
        f"textcolor=color.rgb(195, 194, 183), size=size.tiny)",
    ]


def _trade_plan(plan: TradePlan) -> list[str]:
    """Entry, stop and reward as boxes — a drawing, never an order.

    Worth restating where the code is: this emits *rectangles on a chart*. It
    cannot reach a broker, it carries no size, and TradingView's own Trade panel
    is not a surface any Genesis tool may touch (see genesis-tradingview-mcp
    hard rule 1). A trade plan on the chart is a picture of an intention.
    """
    out = [
        f"box.new(bar_index - 40, {max(plan.entry, plan.stop):.6f}, bar_index + 20, "
        f"{min(plan.entry, plan.stop):.6f}, border_color=color.new(color.rgb(208, 59, 59), 30), "
        f"bgcolor=color.new(color.rgb(208, 59, 59), 85))",
        f"line.new(bar_index - 40, {plan.entry:.6f}, bar_index + 20, {plan.entry:.6f}, "
        f"color=color.white, width=2)",
    ]
    if plan.targets:
        target = plan.targets[-1]
        out.append(
            f"box.new(bar_index - 40, {max(plan.entry, target):.6f}, bar_index + 20, "
            f"{min(plan.entry, target):.6f}, border_color=color.new(color.rgb(12, 163, 12), 30), "
            f"bgcolor=color.new(color.rgb(12, 163, 12), 85))"
        )
    rr = plan.computed_rr
    out.append(
        f"label.new(bar_index + 20, {plan.entry:.6f}, "
        f'"{plan.side.upper()} {plan.entry:,.2f}'
        + (f"  {rr:.1f}R" if rr else "")
        + '", style=label.style_label_left, color=color.new(color.gray, 20), '
        f'textcolor=color.white, size=size.small, tooltip="{_escape(plan.why)}")'
    )
    return out


def _marker(marker: Marker) -> list[str]:
    return [
        f"label.new({_time(marker.time)}, {marker.price:.6f}, "
        f'"{_escape(marker.label)}", xloc=xloc.bar_time, '
        f"style=label.style_circle, color=color.rgb(201, 133, 0), "
        f"textcolor=color.white, size=size.tiny)",
    ]


def _fib(fib: Fib) -> list[str]:
    out = []
    for ratio, price in fib.prices().items():
        out.append(
            f"line.new(bar_index - 200, {price:.6f}, bar_index + 20, {price:.6f}, "
            f"extend=extend.right, style=line.style_dotted, "
            f"color=color.new(color.rgb(137, 135, 129), 40), width=1)"
        )
        out.append(
            f"label.new(bar_index + 20, {price:.6f}, \"{ratio:.3f}\", "
            f"style=label.style_none, textcolor=color.rgb(137, 135, 129), size=size.tiny)"
        )
    return out


def _text(note: TextNote) -> list[str]:
    if note.position is None:
        return []
    return [
        f"label.new({_time(note.position[0])}, {note.position[1]:.6f}, "
        f'"{_escape(note.content)}", xloc=xloc.bar_time, style=label.style_none, '
        f"textcolor=color.rgb(195, 194, 183), size=size.small)",
    ]


def _header_label(spec: MarkupSpec) -> str:
    """A corner stamp naming the spec, so the overlay says what produced it.

    The same discipline as the PNG's burned-in footer: an overlay you cannot
    trace back to a spec is one you cannot check, and after a week you will not
    remember whether it is from this morning or last month.
    """
    trend = spec.structure.trend.upper() if spec.structure.trend else ""
    text = (
        f"GENESIS {spec.symbol} {spec.timeframe}  {trend}  "
        f"{spec.as_of.strftime('%Y-%m-%d %H:%M UTC')}  {spec.id}"
    )
    return (
        "if barstate.islast\n"
        "    var table stamp = table.new(position.top_right, 1, 1)\n"
        f'    table.cell(stamp, 0, 0, "{_escape(text)}", '
        "text_color=color.rgb(137, 135, 129), text_size=size.tiny, "
        "bgcolor=color.new(color.black, 60))"
    )


def _rgb(hex_colour: str) -> str:
    value = hex_colour.lstrip("#")
    return f"{int(value[0:2], 16)}, {int(value[2:4], 16)}, {int(value[4:6], 16)}"


def _alpha(strength: float) -> int:
    """Strength -> Pine transparency (0 opaque, 100 invisible).

    Inverted and clamped so a zero-strength level is faint rather than absent.
    An invisible level is worse than a weak one: it is a level the watcher is
    tracking and you cannot see.
    """
    return int(max(10, min(70, 70 - strength * 55)))


def _escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")


def _time(value: Any) -> int:
    """An ISO timestamp as Pine's epoch milliseconds."""
    if isinstance(value, datetime):
        when = value
    else:
        when = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    return int(when.timestamp() * 1000)
